# Generated by Django 4.2.11 on 2024-04-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_projectmodel_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
